function varargout = PolariX_meas_GUI_export(varargin)
% POLARIX_MEAS_GUI_EXPORT MATLAB code for PolariX_meas_GUI_export.fig
%      POLARIX_MEAS_GUI_EXPORT, by itself, creates a new POLARIX_MEAS_GUI_EXPORT or raises the existing
%      singleton*.
%
%      H = POLARIX_MEAS_GUI_EXPORT returns the handle to a new POLARIX_MEAS_GUI_EXPORT or the handle to
%      the existing singleton*.
%
%      POLARIX_MEAS_GUI_EXPORT('CALLBACK',hObject,eventData,handles,...) calls the local
%      function named CALLBACK in POLARIX_MEAS_GUI_EXPORT.M with the given input arguments.
%
%      POLARIX_MEAS_GUI_EXPORT('Property','Value',...) creates a new POLARIX_MEAS_GUI_EXPORT or raises the
%      existing singleton*.  Starting from the left, property value pairs are
%      applied to the GUI before PolariX_meas_GUI_export_OpeningFcn gets called.  An
%      unrecognized property name or invalid value makes property application
%      stop.  All inputs are passed to PolariX_meas_GUI_export_OpeningFcn via varargin.
%
%      *See GUI Options on GUIDE's Tools menu.  Choose "GUI allows only one
%      instance to run (singleton)".
%
% See also: GUIDE, GUIDATA, GUIHANDLES

% Edit the above text to modify the response to help PolariX_meas_GUI_export

% Last Modified by GUIDE v2.5 28-Aug-2023 17:13:38

% Begin initialization code - DO NOT EDIT
gui_Singleton = 1;
gui_State = struct('gui_Name',       mfilename, ...
                   'gui_Singleton',  gui_Singleton, ...
                   'gui_OpeningFcn', @PolariX_meas_GUI_export_OpeningFcn, ...
                   'gui_OutputFcn',  @PolariX_meas_GUI_export_OutputFcn, ...
                   'gui_LayoutFcn',  @PolariX_meas_GUI_export_LayoutFcn, ...
                   'gui_Callback',   []);
if nargin && ischar(varargin{1})
    gui_State.gui_Callback = str2func(varargin{1});
end

if nargout
    [varargout{1:nargout}] = gui_mainfcn(gui_State, varargin{:});
else
    gui_mainfcn(gui_State, varargin{:});
end
% End initialization code - DO NOT EDIT


% --- Executes just before PolariX_meas_GUI_export is made visible.
function PolariX_meas_GUI_export_OpeningFcn(hObject, eventdata, handles, varargin)
% This function has no output args, see OutputFcn.
% hObject    handle to figure
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% varargin   command line arguments to PolariX_meas_GUI_export (see VARARGIN)

% Choose default command line output for PolariX_meas_GUI_export
handles.output = hObject;

Update_TimeCalInfo(handles)
Update_EnergyCalInfo(handles)

% set the default settings at the opening of the GUI
% handles = initialize_default_settings(handles);

% Update handles structure
guidata(hObject, handles);

% UIWAIT makes PolariX_meas_GUI_export wait for user response (see UIRESUME)
% uiwait(handles.figure1);


% % Set the default settings at the opening of the GUI
% function handle_new = initialize_default_settings(handle_old)
% % default choices at opening
% handle_new = handle_old;
% 
% % for calibration settings
% 
% chosen = get(handle_old.bgrMethod,'Value')-1;
% handle_new.CalibrationBgrMethod = chosen;  % default background method

% chosen = str2double(get(handle_old.edit_CalibrationNumBGR,'String'));
% handle_new.CalibrationBgrNum = chosen;  % default background number
% 
% chosen = str2double(get(handle_old.edit_CalibrationNumIMG,'String'));
% handle_new.CalibrationImgNum = chosen;  % default image number
% 
% chosen = str2double(get(handle_old.edit_CalibrationScanStep,'String'));
% handle_new.CalibrationScanStep = chosen;  % default scan steps
% 
% chosen = get(handle_old.checkbox_CalibrationWaitForTimeReso,'Value');
% handle_new.CalibrationWaitForTimeReso = chosen;  % default setting for waiting before proceed with time resolution measurement
% 
% % for measurement settings
% chosen = get(handle_old.popupmenu_MeasurementBgrMethod,'Value')-1;
% handle_new.MeasurementBgrMethod = chosen;  % default background method
% 
% chosen = str2double(get(handle_old.edit_MeasurementNumBGR,'String'));
% handle_new.MeasurementBgrNum = chosen;  % default background number
% 
% chosen = str2double(get(handle_old.edit_MeasurementNumIMG,'String'));
% handle_new.MeasurementImgNum = chosen;  % default image number
% 
% % for measurement settings
% contents = cellstr(get(handle_old.popupmenu_gainMode,'String'));
% gainMode = contents{get(handle_old.popupmenu_gainMode,'Value')};
% handle_new.gainMode = gainMode;  % default adjust gain mode


% --- Outputs from this function are returned to the command line.
function varargout = PolariX_meas_GUI_export_OutputFcn(hObject, eventdata, handles) 
% varargout  cell array for returning output args (see VARARGOUT);
% hObject    handle to figure
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Get default command line output from handles structure
varargout{1} = handles.output;






% --- Executes on button press in togglebutton1.
function togglebutton1_Callback(hObject, eventdata, handles)
% hObject    handle to togglebutton1 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hint: get(hObject,'Value') returns toggle state of togglebutton1


% --- Executes on button press in doTimeCali.
function doTimeCali_Callback(hObject, eventdata, handles)
% hObject    handle to doTimeCali (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
if ~isempty(get(handles.phaseLeft,'String')) && ~isempty(get(handles.phaseRight,'String'))

    msgLoc = handles.txtOut;
    display_message(msgLoc, 'STARTING TIME CALIBRATION - sit back and relax. :-)');
    
	phase_left = str2double(get(handles.phaseLeft,'String'));
	phase_right = str2double(get(handles.phaseRight,'String'));
    
    bgrMethod = get(handles.bgrMethod,'Value')-1;
    numBgr = str2double(get(handles.numBgr,'String'));
    numSig = str2double(get(handles.numSig,'String'));
    numStep = str2double(get(handles.numStep,'String'));
    
    comment = get(handles.comment,'String');

    try
        get_timecalibration_OTR9FL2XTDS(phase_left, phase_right, bgrMethod, numBgr, numSig, numStep, msgLoc, comment)
    end
    
    Update_TimeCalInfo(handles)
    display_message(msgLoc, 'FINISHED TIME CALIBRATION.');
end


% --- Executes on button press in doTimeCaliFast.
function doTimeCaliFast_Callback(hObject, eventdata, handles)
% hObject    handle to doTimeCaliFast (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
if ~isempty(get(handles.phaseLeft,'String')) && ~isempty(get(handles.phaseRight,'String'))

    msgLoc = handles.txtOut;
    display_message(msgLoc, 'STARTING FAST TIME CALIBRATION  - sit back and relax. :-)');
    
	phase_left = str2double(get(handles.phaseLeft,'String'));
	phase_right = str2double(get(handles.phaseRight,'String'));
    
    bgrMethod = get(handles.bgrMethod,'Value')-1;
    numBgr = str2double(get(handles.numBgr,'String'));
    numSig = str2double(get(handles.numSig,'String'));
    numStep = str2double(get(handles.numStep,'String'));
    
    comment = get(handles.comment,'String');
    
    try
        get_timecalibration_fast_OTR9FL2XTDS(phase_left, phase_right, bgrMethod, numBgr, numSig, numStep, msgLoc, comment)
    end
    
    Update_TimeCalInfo(handles)
    display_message(msgLoc, 'FINISHED FAST TIME CALIBRATION.');
end

% --- Executes on button press in doTimeCaliFastDouble.
function doTimeCaliFastDouble_Callback(hObject, eventdata, handles)
% hObject    handle to doTimeCaliFastDouble (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
if ~isempty(get(handles.phaseLeft,'String')) && ~isempty(get(handles.phaseRight,'String'))

    msgLoc = handles.txtOut;
    display_message(msgLoc, 'STARTING FAST TIME CALIBRATION in two directions - sit back and relax. :-)');
    
	phase_left = str2double(get(handles.phaseLeft,'String'));
	phase_right = str2double(get(handles.phaseRight,'String'));
    
    bgrMethod = get(handles.bgrMethod,'Value')-1;
    numBgr = str2double(get(handles.numBgr,'String'));
    numSig = str2double(get(handles.numSig,'String'));
    numStep = str2double(get(handles.numStep,'String'));
    
    comment = get(handles.comment,'String');
    
    try
        get_timecalibration_fast_double_OTR9FL2XTDS(phase_left, phase_right, bgrMethod, numBgr, numSig, numStep, msgLoc, comment)
    end
    
    Update_TimeCalInfo(handles)
    
    display_message(msgLoc, 'FINISHED FAST TIME CALIBRATION in two directions.');
end

% --- Executes on button press in doEnergyCali.
function doEnergyCali_Callback(hObject, eventdata, handles)
% hObject    handle to doEnergyCali (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
if ~isempty(get(handles.currentTop,'String')) && ~isempty(get(handles.currentBottom,'String'))

    msgLoc = handles.txtOut;
    display_message(msgLoc, 'STARTING ENERGY CALIBRATION - sit back and relax. :-)');
    
	currentTop = str2double(get(handles.currentTop,'String'));
	currentBottom = str2double(get(handles.currentBottom,'String'));
    
    bgrMethod = get(handles.bgrMethod,'Value')-1;
    numBgr = str2double(get(handles.numBgr,'String'));
    numSig = str2double(get(handles.numSig,'String'));
    numStep = str2double(get(handles.numStep,'String'));
    
    comment = get(handles.comment,'String');
    
    try
        get_energycalibration_OTR9FL2XTDS(currentTop, currentBottom, bgrMethod, numBgr, numSig, numStep, msgLoc, comment)
    end
    
    Update_EnergyCalInfo(handles)
    
    display_message(msgLoc, 'FINISHED ENERGY CALIBRATION.');
end
%%%%%%
% we need to add another collibration here 
function energy_colli_with_cycling_Callback(hObject, eventdata, handles)
% hObject    handle to doEnergyCali (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
if ~isempty(get(handles.currentTop,'String')) && ~isempty(get(handles.currentBottom,'String'))

    msgLoc = handles.txtOut;
    display_message(msgLoc, 'STARTING ENERGY CALIBRATION - sit back and relax. :-)');
    
	currentTop = str2double(get(handles.currentTop,'String'));
	currentBottom = str2double(get(handles.currentBottom,'String'));
    
    bgrMethod = get(handles.bgrMethod,'Value')-1;
    numBgr = str2double(get(handles.numBgr,'String'));
    numSig = str2double(get(handles.numSig,'String'));
    numStep = str2double(get(handles.numStep,'String'));
     
    comment = get(handles.comment,'String');
    
    try
        get_energycalibration_cycling(currentTop, currentBottom, bgrMethod, numBgr, numSig, numStep, msgLoc, comment)
    end
    
    Update_EnergyCalInfo(handles)
    
    display_message(msgLoc, 'FINISHED ENERGY CALIBRATION.');
end
%%%%%
% --- Executes on button press in doMeasurement.
function doMeasurement_Callback(hObject, eventdata, handles)
% hObject    handle to doMeasurement (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
    msgLoc = handles.txtOut;
    display_message(msgLoc, 'STARTING DATA TAKING - sit back and relax. :-)');
    
    bgrMethod = get(handles.bgrMethod,'Value')-1;
    numBgr = str2double(get(handles.numBgr,'String'));
    numSig = str2double(get(handles.numSig,'String'));
%     numStep = str2double(get(handles.numStep,'String'));
    
    comment = get(handles.comment,'String');
    get_calibratedimage_OTR9FL2XTDS(bgrMethod, numBgr, numSig, msgLoc, comment)  
    display_message(msgLoc, 'FINISHED DATA TAKING');


% --- Executes on button press in loadTimeCali.
function loadTimeCali_Callback(hObject, eventdata, handles)
% hObject    handle to loadTimeCali (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

strPattern = ['timecalibration*.mat'];
dialogTitle = 'time calibration file';
folderpath = ['time_calibration/'];

filename_timecal = selectFiles_for_popupmenu(hObject, strPattern,dialogTitle,folderpath);
load([folderpath, filename_timecal], 'amplitude_XTDS', 'timecal_fspixel', 'timecal_fspixel_err', 'timecal_streak', 'timestamp')
save('/home/ttflinac/user/mflorian/PolariX/FL2/time_calibration/time_calib_9FLFXTDS.mat', 'amplitude_XTDS', 'timecal_fspixel', 'timecal_fspixel_err', 'timecal_streak', 'timestamp')
Update_TimeCalInfo(handles)

% --- Executes on button press in loadEnergyCali.
function loadEnergyCali_Callback(hObject, eventdata, handles)
% hObject    handle to loadEnergyCali (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
strPattern = ['energycalibration*.mat'];
dialogTitle = 'energy calibration file';
folderpath = ['energy_calibration/'];

filename_energycal = selectFiles_for_popupmenu(hObject, strPattern,dialogTitle,folderpath);
load([folderpath, filename_energycal], 'ergcal', 'ergcal_err', 'timestamp')
save('/home/ttflinac/user/mflorian/PolariX/FL2/time_calibration/erg_calib_9FLFXTDS.mat', 'amplitude_XTDS', 'timecal_fspixel', 'timecal_fspixel_err', 'timecal_streak', 'timestamp')
Update_TimeCalInfo(handles)

function filename = selectFiles_for_popupmenu(hPopupmenu, strPattern,dialogTitle,folderpath)

% filename_old = get(hPopupmenu,'String');

[filename,pathname] = uigetfile(strPattern, dialogTitle, folderpath);


function phaseRight_Callback(hObject, eventdata, handles)
% hObject    handle to phaseRight (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject,'String') returns contents of phaseRight as text
%        str2double(get(hObject,'String')) returns contents of phaseRight as a double


% --- Executes during object creation, after setting all properties.
function phaseRight_CreateFcn(hObject, eventdata, handles)
% hObject    handle to phaseRight (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end



function phaseLeft_Callback(hObject, eventdata, handles)
% hObject    handle to phaseLeft (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject,'String') returns contents of phaseLeft as text
%        str2double(get(hObject,'String')) returns contents of phaseLeft as a double


% --- Executes during object creation, after setting all properties.
function phaseLeft_CreateFcn(hObject, eventdata, handles)
% hObject    handle to phaseLeft (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end


% --- Executes on button press in pushbutton2.
function pushbutton2_Callback(hObject, eventdata, handles)
% hObject    handle to pushbutton2 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)


% --- Executes on button press in refreshTimeCali.
function refreshTimeCali_Callback(hObject, eventdata, handles)
% hObject    handle to refreshTimeCali (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% display_message(handles.txtOut , 'test')

Update_TimeCalInfo(handles)


% --- Executes on button press in readLeftPhase.
function readLeftPhase_Callback(hObject, eventdata, handles)
% hObject    handle to readLeftPhase (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% read left phase
try
    PolariX_phase = 'FLASH.RF/LLRF.CONTROLLER/CTRL.POLARIX/SP.PHASE';
    current_phase = hlcr(PolariX_phase);
    set(handles.phaseLeft,'String',num2str(current_phase, '%.1f'));
end


% --- Executes on button press in readRightPhase.
function readRightPhase_Callback(hObject, eventdata, handles)
% hObject    handle to readRightPhase (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% read left phase
try
    PolariX_phase = 'FLASH.RF/LLRF.CONTROLLER/CTRL.POLARIX/SP.PHASE';
    current_phase = hlcr(PolariX_phase);
    set(handles.phaseRight,'String',num2str(current_phase, '%.1f'));
end




function currentBottom_Callback(hObject, eventdata, handles)
% hObject    handle to currentBottom (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject,'String') returns contents of currentBottom as text
%        str2double(get(hObject,'String')) returns contents of currentBottom as a double


% --- Executes during object creation, after setting all properties.
function currentBottom_CreateFcn(hObject, eventdata, handles)
% hObject    handle to currentBottom (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end



function currentTop_Callback(hObject, eventdata, handles)
% hObject    handle to currentTop (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject,'String') returns contents of currentTop as text
%        str2double(get(hObject,'String')) returns contents of currentTop as a double


% --- Executes during object creation, after setting all properties.
function currentTop_CreateFcn(hObject, eventdata, handles)
% hObject    handle to currentTop (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end


% --- Executes on button press in pushbutton10.
function pushbutton10_Callback(hObject, eventdata, handles)
% hObject    handle to pushbutton10 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)


% --- Executes on button press in readTopCurrent.
function readTopCurrent_Callback(hObject, eventdata, handles)
% hObject    handle to readTopCurrent (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
try
    
    %current_current = hlcr('TTF2.MAGNETS/DIPOLE/D9SMATCH/PS');
    current_current = hlcr('FLASH.MAGNETS/MAGNET.ML/D4FL2XTDS/CURRENT.SP');
    set(handles.currentTop,'String',num2str(current_current, '%.1f'));
end

% --- Executes on button press in readBottomCurrent.
function readBottomCurrent_Callback(hObject, eventdata, handles)
% hObject    handle to readBottomCurrent (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
try
    
    %current_current = hlcr('TTF2.MAGNETS/DIPOLE/D9SMATCH/PS');
    current_current = hlcr('FLASH.MAGNETS/MAGNET.ML/D4FL2XTDS/CURRENT.SP');
    set(handles.currentBottom,'String',num2str(current_current, '%.1f'));
end




function numStep_Callback(hObject, eventdata, handles)                                                                       % Not clear to me (N)
% hObject    handle to numStep (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject,'String') returns contents of numStep as text
%        str2double(get(hObject,'String')) returns contents of numStep as a double


% --- Executes during object creation, after setting all properties.
function numStep_CreateFcn(hObject, eventdata, handles)
% hObject    handle to numStep (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end



function numSig_Callback(hObject, eventdata, handles)                                                                       % Not clear to me (N)
% hObject    handle to numSig (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject,'String') returns contents of numSig as text
%        str2double(get(hObject,'String')) returns contents of numSig as a double


% --- Executes during object creation, after setting all properties.
function numSig_CreateFcn(hObject, eventdata, handles)
% hObject    handle to numSig (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end



function numBgr_Callback(hObject, eventdata, handles)
% hObject    handle to numBgr (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject,'String') returns contents of numBgr as text
%        str2double(get(hObject,'String')) returns contents of numBgr as a double


% --- Executes during object creation, after setting all properties.
function numBgr_CreateFcn(hObject, eventdata, handles)
% hObject    handle to numBgr (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end


% --- Executes on selection change in bgrMethod.
function bgrMethod_Callback(hObject, eventdata, handles)
% hObject    handle to bgrMethod (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: contents = cellstr(get(hObject,'String')) returns bgrMethod contents as cell array
%        contents{get(hObject,'Value')} returns selected item from bgrMethod


% --- Executes during object creation, after setting all properties.
function bgrMethod_CreateFcn(hObject, eventdata, handles)
% hObject    handle to bgrMethod (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: popupmenu controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end



function Update_TimeCalInfo(handles)
try
    load('/home/ttflinac/user/mflorian/PolariX/FL2/time_calibration/time_calib_9FL2XTDS.mat', 'amplitude_XTDS', 'timecal_fspixel', 'timecal_fspixel_err', 'timecal_streak', 'timestamp')

    set(handles.timeCaliTimeStamp,'String',timestamp);
    set(handles.timeCaliValue,'String',[num2str(timecal_fspixel, '%.3f'), '+-', num2str(timecal_fspixel_err, '%.3f') ' fs/pixel, Streak: ', num2str(timecal_streak, '%.1f')])
catch
    set(handles.timeCaliTimeStamp,'String','no old time cali file available');
end

function Update_EnergyCalInfo(handles)
try
    load('/home/ttflinac/user/mflorian/PolariX/FL2/energy_calibration/erg_calib_9FL2XTDS.mat', 'ergcal', 'ergcal_err', 'timestamp')
catch
    set(handles.timeCaliTimeStamp,'String','no old energy cali file available');
end

set(handles.energyCaliTimeStamp,'String',timestamp);
set(handles.energyCaliValue,'String',[num2str(ergcal*10, '%.3f'), '+-', num2str(ergcal_err*10, '%.3f') ' *1e-4/pixel'])


% --- Executes on selection change in txtOut.
function txtOut_Callback(hObject, eventdata, handles)
% hObject    handle to txtOut (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: contents = cellstr(get(hObject,'String')) returns txtOut contents as cell array
%        contents{get(hObject,'Value')} returns selected item from txtOut


% --- Executes during object creation, after setting all properties.
function txtOut_CreateFcn(hObject, eventdata, handles)
% hObject    handle to txtOut (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: listbox controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end



function comment_Callback(hObject, eventdata, handles)
% hObject    handle to comment (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject,'String') returns contents of comment as text
%        str2double(get(hObject,'String')) returns contents of comment as a double


% --- Executes during object creation, after setting all properties.
function comment_CreateFcn(hObject, eventdata, handles)
% hObject    handle to comment (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end


% --- Executes on button press in pushbutton18.
function pushbutton18_Callback(hObject, eventdata, handles)
% hObject    handle to pushbutton18 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)


% --- Creates and returns a handle to the GUI figure. 
function h1 = PolariX_meas_GUI_export_LayoutFcn(policy)
% policy - create a new figure or use a singleton. 'new' or 'reuse'.

persistent hsingleton;
if strcmpi(policy, 'reuse') & ishandle(hsingleton)
    h1 = hsingleton;
    return;
end
load PolariX_meas_GUI_export.mat


appdata = [];
appdata.GUIDEOptions = struct(...
    'active_h', [], ...
    'taginfo', struct(...
    'figure', 2, ...
    'text', 26, ...
    'uipanel', 4, ...
    'togglebutton', 2, ...
    'pushbutton', 18, ...
    'edit', 9, ...
    'checkbox', 2, ...
    'popupmenu', 2, ...
    'listbox', 2), ...
    'override', 0, ...
    'release', [], ...
    'resize', 'none', ...
    'accessibility', 'callback', ...
    'mfile', 1, ...
    'callbacks', 1, ...
    'singleton', 1, ...
    'syscolorfig', 1, ...
    'blocking', 0, ...
    'lastSavedFile', '/System/Volumes/Data/home/ttflinac/user/mirian/FL2 copy/PolariX_meas_GUI_export.m', ...
    'lastFilename', '/System/Volumes/Data/home/ttflinac/user/mirian/FL2 copy/PolariX_meas_GUI.fig');
appdata.lastValidTag = 'figure1';
appdata.GUIDELayoutEditor = mat{1};

h1 = figure(...
'PaperUnits',get(0,'defaultfigurePaperUnits'),...
'Units','characters',...
'Position',[181.066666666667 55.7794871794871 149.833333333333 56.7333333333333],...
'Visible',get(0,'defaultfigureVisible'),...
'Color',get(0,'defaultfigureColor'),...
'CloseRequestFcn',get(0,'defaultfigureCloseRequestFcn'),...
'CurrentAxesMode','manual',...
'CurrentObjectMode','manual',...
'CurrentPointMode','manual',...
'SelectionTypeMode','manual',...
'ResizeFcn',blanks(0),...
'IntegerHandle','off',...
'NextPlot',get(0,'defaultfigureNextPlot'),...
'Alphamap',get(0,'defaultfigureAlphamap'),...
'Colormap',get(0,'defaultfigureColormap'),...
'WindowButtonDownFcn',blanks(0),...
'WindowButtonUpFcn',blanks(0),...
'WindowButtonMotionFcn',blanks(0),...
'WindowScrollWheelFcn',blanks(0),...
'WindowKeyPressFcn',blanks(0),...
'WindowKeyReleaseFcn',blanks(0),...
'MenuBar','none',...
'ToolBar','none',...
'Pointer',get(0,'defaultfigurePointer'),...
'PointerShapeHotSpot',get(0,'defaultfigurePointerShapeHotSpot'),...
'Name','PolariX_meas_GUI',...
'NumberTitle','off',...
'HandleVisibility','callback',...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','figure1',...
'UserData',[],...
'WindowStyle',get(0,'defaultfigureWindowStyle'),...
'DockControls',get(0,'defaultfigureDockControls'),...
'Resize','off',...
'PaperPosition',get(0,'defaultfigurePaperPosition'),...
'PaperSize',get(0,'defaultfigurePaperSize'),...
'PaperType',get(0,'defaultfigurePaperType'),...
'InvertHardcopy',get(0,'defaultfigureInvertHardcopy'),...
'PaperOrientation',get(0,'defaultfigurePaperOrientation'),...
'ScreenPixelsPerInchMode','manual',...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0));

appdata = [];
appdata.lastValidTag = 'uipanel1';

h2 = uipanel(...
'Parent',h1,...
'FontUnits',get(0,'defaultuipanelFontUnits'),...
'Units','pixels',...
'Title','Time calibration',...
'BackgroundColor',[0.941176470588235 0.941176470588235 0.941176470588235],...
'ResizeFcn',blanks(0),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','uipanel1',...
'Clipping','off',...
'Position',[30 551 361 245],...
'Layout',[],...
'FontSize',12);

appdata = [];
appdata.lastValidTag = 'text2';

h3 = uicontrol(...
'Parent',h2,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment','left',...
'String',{  'Select the PolariX RF phases, at which the beam'; 'is on the left and right edge of the screen'; blanks(0) },...
'Style','text',...
'Position',[0.0196078431372549 0.827106111261709 0.963585434173669 0.155555555555556],...
'BackgroundColor',[0.941176470588235 0.941176470588235 0.941176470588235],...
'Children',[],...
'ForegroundColor',[0.501960784313725 0.501960784313725 0.501960784313725],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text2',...
'FontSize',9.99999999999989);

appdata = [];
appdata.lastValidTag = 'textTimeCaliLog';

h4 = uicontrol(...
'Parent',h2,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String',{  blanks(0); blanks(0) },...
'Style','text',...
'Position',[0.0476190476190476 0.277056277056277 0.599439775910364 0.147186147186147],...
'BackgroundColor',[0.941176470588235 0.941176470588235 0.941176470588235],...
'Children',[],...
'ForegroundColor',[0.847058823529412 0.16078431372549 0],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','textTimeCaliLog',...
'FontSize',9.99999999999989);

appdata = [];
appdata.lastValidTag = 'text4';

h5 = uicontrol(...
'Parent',h2,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String',{  'right'; blanks(0) },...
'Style','text',...
'Position',[0.34733893557423 0.745689655172414 0.19327731092437 0.0991379310344828],...
'BackgroundColor',[0.941176470588235 0.941176470588235 0.941176470588235],...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text4',...
'FontSize',10.9999999999998);

appdata = [];
appdata.lastValidTag = 'text5';

h6 = uicontrol(...
'Parent',h2,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','left',...
'Style','text',...
'Position',[0.0448179271708683 0.788793103448276 0.266106442577031 0.0603448275862069],...
'BackgroundColor',[0.941176470588235 0.941176470588235 0.941176470588235],...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text5',...
'FontSize',10.9999999999998);

appdata = [];
appdata.lastValidTag = 'doTimeCali';

h7 = uicontrol(...
'Parent',h2,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','do time-calibration',...
'Position',[0.669467787114846 0.636363636363636 0.313725490196078 0.0995670995670995],...
'BackgroundColor',[0.941176470588235 0.941176470588235 0.941176470588235],...
'Callback',@(hObject,eventdata)PolariX_meas_GUI_export('doTimeCali_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','doTimeCali',...
'KeyPressFcn',blanks(0),...
'FontSize',10.9999999999998);

appdata = [];
appdata.lastValidTag = 'phaseRight';

h8 = uicontrol(...
'Parent',h2,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String',blanks(0),...
'Style','edit',...
'Position',[0.358543417366947 0.599137931034483 0.168067226890756 0.146551724137931],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)PolariX_meas_GUI_export('phaseRight_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)PolariX_meas_GUI_export('phaseRight_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','phaseRight',...
'KeyPressFcn',blanks(0),...
'FontSize',9.99999999999989);

appdata = [];
appdata.lastValidTag = 'phaseLeft';

h9 = uicontrol(...
'Parent',h2,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String',blanks(0),...
'Style','edit',...
'Position',[0.092436974789916 0.599137931034483 0.168067226890756 0.155172413793103],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)PolariX_meas_GUI_export('phaseLeft_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)PolariX_meas_GUI_export('phaseLeft_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','phaseLeft',...
'KeyPressFcn',blanks(0),...
'FontSize',9.99999999999989);

appdata = [];
appdata.lastValidTag = 'text6';

h10 = uicontrol(...
'Parent',h2,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','last calibration: ',...
'Style','text',...
'Position',[0.00560224089635854 0.133333333333333 0.235294117647059 0.0777777777777778],...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text6',...
'FontSize',9.99999999999989);

appdata = [];
appdata.lastValidTag = 'text7';

h11 = uicontrol(...
'Parent',h2,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','value:',...
'Style','text',...
'Position',[0.0168067226890756 0.0388888888888889 0.218487394957983 0.0777777777777778],...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text7',...
'FontSize',9.99999999999989);

appdata = [];
appdata.lastValidTag = 'timeCaliTimeStamp';

h12 = uicontrol(...
'Parent',h2,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String',blanks(0),...
'Style','text',...
'Position',[0.246498599439776 0.133333333333333 0.565826330532213 0.0888888888888889],...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','timeCaliTimeStamp',...
'FontSize',9.99999999999989);

appdata = [];
appdata.lastValidTag = 'timeCaliValue';

h13 = uicontrol(...
'Parent',h2,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String',blanks(0),...
'Style','text',...
'Position',[0.246498599439776 0.0388888888888889 0.532212885154062 0.0777777777777778],...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','timeCaliValue',...
'FontSize',9.99999999999989);

appdata = [];
appdata.lastValidTag = 'refreshTimeCali';

h14 = uicontrol(...
'Parent',h2,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','Refresh',...
'Position',[0.84593837535014 0.0517241379310345 0.140056022408964 0.146551724137931],...
'Callback',@(hObject,eventdata)PolariX_meas_GUI_export('refreshTimeCali_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','refreshTimeCali',...
'KeyPressFcn',blanks(0),...
'FontSize',10.9999999999998);

appdata = [];
appdata.lastValidTag = 'readLeftPhase';

h15 = uicontrol(...
'Parent',h2,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','read phase',...
'Position',[0.0784313725490196 0.478448275862069 0.196078431372549 0.0991379310344828],...
'BackgroundColor',[0.941176470588235 0.941176470588235 0.941176470588235],...
'Callback',@(hObject,eventdata)PolariX_meas_GUI_export('readLeftPhase_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','readLeftPhase',...
'KeyPressFcn',blanks(0),...
'FontSize',10.9999999999998);

appdata = [];
appdata.lastValidTag = 'readRightPhase';

h16 = uicontrol(...
'Parent',h2,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','read phase',...
'Position',[0.34453781512605 0.478448275862069 0.196078431372549 0.0991379310344828],...
'BackgroundColor',[0.941176470588235 0.941176470588235 0.941176470588235],...
'Callback',@(hObject,eventdata)PolariX_meas_GUI_export('readRightPhase_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','readRightPhase',...
'KeyPressFcn',blanks(0),...
'FontSize',10.9999999999998);

appdata = [];
appdata.lastValidTag = 'loadTimeCali';

h17 = uicontrol(...
'Parent',h2,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','load time-calibration',...
'Position',[0.669467787114846 0.307359307359307 0.313725490196078 0.0995670995670996],...
'BackgroundColor',[0.941176470588235 0.941176470588235 0.941176470588235],...
'Callback',@(hObject,eventdata)PolariX_meas_GUI_export('loadTimeCali_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','loadTimeCali',...
'KeyPressFcn',blanks(0),...
'FontSize',10.9999999999998);

appdata = [];
appdata.lastValidTag = 'doTimeCaliFast';

h18 = uicontrol(...
'Parent',h2,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','time-calibration fast',...
'Position',[0.669467787114846 0.532467532467532 0.313725490196078 0.0995670995670995],...
'BackgroundColor',[0.941176470588235 0.941176470588235 0.941176470588235],...
'Callback',@(hObject,eventdata)PolariX_meas_GUI_export('doTimeCaliFast_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','doTimeCaliFast',...
'KeyPressFcn',blanks(0),...
'FontSize',10.9999999999998);

appdata = [];
appdata.lastValidTag = 'doTimeCaliFastDouble';

h19 = uicontrol(...
'Parent',h2,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','time-cali fast double',...
'Position',[0.669467787114846 0.428571428571429 0.313725490196078 0.0995670995670996],...
'BackgroundColor',[0.941176470588235 0.941176470588235 0.941176470588235],...
'Callback',@(hObject,eventdata)PolariX_meas_GUI_export('doTimeCaliFastDouble_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','doTimeCaliFastDouble',...
'KeyPressFcn',blanks(0),...
'FontSize',10.9999999999998);

appdata = [];
appdata.lastValidTag = 'uipanel2';

h20 = uipanel(...
'Parent',h1,...
'FontUnits',get(0,'defaultuipanelFontUnits'),...
'Units','pixels',...
'Title','Energy calibration',...
'BackgroundColor',[0.941176470588235 0.941176470588235 0.941176470588235],...
'ResizeFcn',blanks(0),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','uipanel2',...
'Clipping','off',...
'Position',[30 284 371 245],...
'Layout',[],...
'FontSize',12);

appdata = [];
appdata.lastValidTag = 'textEnergyCaliLog';

h21 = uicontrol(...
'Parent',h20,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String',{  blanks(0); blanks(0) },...
'Style','text',...
'Position',[0.0480192076830732 0.275710380555633 0.698679471788715 0.147619047619048],...
'BackgroundColor',[0.941176470588235 0.941176470588235 0.941176470588235],...
'Children',[],...
'ForegroundColor',[0.847058823529412 0.16078431372549 0],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','textEnergyCaliLog',...
'FontSize',9.99999999999989);

appdata = [];
appdata.lastValidTag = 'text12';

h22 = uicontrol(...
'Parent',h20,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String',{  'bottom'; blanks(0) },...
'Style','text',...
'Position',[0.309191796609652 0.745689655172414 0.19327731092437 0.0991379310344828],...
'BackgroundColor',[0.941176470588235 0.941176470588235 0.941176470588235],...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text12',...
'FontSize',10.9999999999998);

appdata = [];
appdata.lastValidTag = 'text13';

h23 = uicontrol(...
'Parent',h20,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','top',...
'Style','text',...
'Position',[0.0448179271708683 0.788793103448276 0.266106442577031 0.0603448275862069],...
'BackgroundColor',[0.941176470588235 0.941176470588235 0.941176470588235],...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text13',...
'FontSize',10.9999999999998);

appdata = [];
appdata.lastValidTag = 'doEnergyCali';

h24 = uicontrol(...
'Parent',h20,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','do energy-calibration',...
'Position',[0.658263305322129 0.718614718614719 0.313725490196078 0.0995670995670995],...
'BackgroundColor',[0.941176470588235 0.941176470588235 0.941176470588235],...
'Callback',@(hObject,eventdata)PolariX_meas_GUI_export('doEnergyCali_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','doEnergyCali',...
'KeyPressFcn',blanks(0),...
'FontSize',10.9999999999998);

appdata = [];
appdata.lastValidTag = 'currentBottom';

h25 = uicontrol(...
'Parent',h20,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String',blanks(0),...
'Style','edit',...
'Position',[0.314946687121715 0.599137931034483 0.168067226890756 0.146551724137931],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)PolariX_meas_GUI_export('currentBottom_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)PolariX_meas_GUI_export('currentBottom_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','currentBottom',...
'KeyPressFcn',blanks(0),...
'FontSize',9.99999999999989);

appdata = [];
appdata.lastValidTag = 'currentTop';

h26 = uicontrol(...
'Parent',h20,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String',blanks(0),...
'Style','edit',...
'Position',[0.092436974789916 0.599137931034483 0.168067226890756 0.155172413793103],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)PolariX_meas_GUI_export('currentTop_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)PolariX_meas_GUI_export('currentTop_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','currentTop',...
'KeyPressFcn',blanks(0),...
'FontSize',9.99999999999989);

appdata = [];
appdata.lastValidTag = 'text14';

h27 = uicontrol(...
'Parent',h20,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','last calibration: ',...
'Style','text',...
'Position',[0.00560224089635854 0.133333333333333 0.235294117647059 0.0777777777777778],...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text14',...
'FontSize',9.99999999999989);

appdata = [];
appdata.lastValidTag = 'text15';

h28 = uicontrol(...
'Parent',h20,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','value:',...
'Style','text',...
'Position',[0.0168067226890756 0.0388888888888889 0.218487394957983 0.0777777777777778],...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text15',...
'FontSize',9.99999999999989);

appdata = [];
appdata.lastValidTag = 'energyCaliTimeStamp';

h29 = uicontrol(...
'Parent',h20,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String',blanks(0),...
'Style','text',...
'Position',[0.246498599439776 0.133333333333333 0.565826330532213 0.0888888888888889],...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','energyCaliTimeStamp',...
'FontSize',9.99999999999989);

appdata = [];
appdata.lastValidTag = 'energyCaliValue';

h30 = uicontrol(...
'Parent',h20,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String',blanks(0),...
'Style','text',...
'Position',[0.246498599439776 0.0388888888888889 0.532212885154062 0.0777777777777778],...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','energyCaliValue',...
'FontSize',9.99999999999989);

appdata = [];
appdata.lastValidTag = 'pushbutton10';

h31 = uicontrol(...
'Parent',h20,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','Refresh',...
'Position',[0.84593837535014 0.0517241379310345 0.140056022408964 0.146551724137931],...
'Callback',@(hObject,eventdata)PolariX_meas_GUI_export('pushbutton10_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton10',...
'KeyPressFcn',blanks(0),...
'FontSize',10.9999999999998);

appdata = [];
appdata.lastValidTag = 'readTopCurrent';

h32 = uicontrol(...
'Parent',h20,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','read current',...
'Position',[0.0784313725490196 0.478448275862069 0.196078431372549 0.0991379310344828],...
'BackgroundColor',[0.941176470588235 0.941176470588235 0.941176470588235],...
'Callback',@(hObject,eventdata)PolariX_meas_GUI_export('readTopCurrent_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','readTopCurrent',...
'KeyPressFcn',blanks(0),...
'FontSize',10.9999999999998);

appdata = [];
appdata.lastValidTag = 'readBottomCurrent';

h33 = uicontrol(...
'Parent',h20,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','read current',...
'Position',[0.311840267442127 0.478448275862069 0.196078431372549 0.0991379310344828],...
'BackgroundColor',[0.941176470588235 0.941176470588235 0.941176470588235],...
'Callback',@(hObject,eventdata)PolariX_meas_GUI_export('readBottomCurrent_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','readBottomCurrent',...
'KeyPressFcn',blanks(0),...
'FontSize',10.9999999999998);

appdata = [];
appdata.lastValidTag = 'loadEnergyCali';

h34 = uicontrol(...
'Parent',h20,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','load energy-calibration',...
'Position',[0.613445378151261 0.285714285714286 0.358543417366947 0.0995670995670996],...
'BackgroundColor',[0.941176470588235 0.941176470588235 0.941176470588235],...
'Callback',@(hObject,eventdata)PolariX_meas_GUI_export('loadEnergyCali_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','loadEnergyCali',...
'KeyPressFcn',blanks(0),...
'FontSize',10.9999999999998);

appdata = [];
appdata.lastValidTag = 'text18';

h35 = uicontrol(...
'Parent',h20,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment','left',...
'String',{  'Select the currents of the Dipole D4FL2XTDS, at which the beam'; 'is on the upper and lower edge of the screen'; blanks(0) },...
'Style','text',...
'Position',[0.0280112044817927 0.835497835497836 0.963585434173669 0.155844155844156],...
'BackgroundColor',[0.941176470588235 0.941176470588235 0.941176470588235],...
'Children',[],...
'ForegroundColor',[0.501960784313725 0.501960784313725 0.501960784313725],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text18',...
'FontSize',9.99999999999989);

appdata = [];
appdata.lastValidTag = 'energy_colli_with_cycling';

h36 = uicontrol(...
'Parent',h20,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','do energy-calibration with Cycling',...
'Position',[0.485013623978202 0.619047619047619 0.512261580381471 0.0995670995670995],...
'BackgroundColor',[0.941176470588235 0.941176470588235 0.941176470588235],...
'Callback',@(hObject,eventdata)PolariX_meas_GUI_export('energy_colli_with_cycling_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','energy_colli_with_cycling',...
'KeyPressFcn',blanks(0),...
'FontSize',10.9999999999998);

appdata = [];
appdata.lastValidTag = 'doMeasurement';

h37 = uicontrol(...
'Parent',h1,...
'Units',get(0,'defaultuicontrolUnits'),...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','do single measurement',...
'Position',[592 739 129 42],...
'BackgroundColor',[0.941176470588235 0.941176470588235 0.941176470588235],...
'Callback',@(hObject,eventdata)PolariX_meas_GUI_export('doMeasurement_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','doMeasurement',...
'KeyPressFcn',blanks(0),...
'FontSize',10.9999999999997);

appdata = [];
appdata.lastValidTag = 'heading';

h38 = uicontrol(...
'Parent',h1,...
'Units',get(0,'defaultuicontrolUnits'),...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','FL2 PolariX Measurement GUI',...
'Style','text',...
'Position',[260 810.846153846154 341 31],...
'Children',[],...
'Tag','heading',...
'FontSize',20,...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'uipanel3';

h39 = uipanel(...
'Parent',h1,...
'FontUnits',get(0,'defaultuipanelFontUnits'),...
'Units','pixels',...
'Title','Camera settings',...
'BackgroundColor',[0.941176470588235 0.941176470588235 0.941176470588235],...
'ResizeFcn',blanks(0),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','uipanel3',...
'Clipping','off',...
'Position',[30 20 361 231],...
'Layout',[],...
'FontSize',12);

appdata = [];
appdata.lastValidTag = 'text21';

h40 = uicontrol(...
'Parent',h39,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','Scan steps',...
'Style','text',...
'Position',[0.0224089635854342 0.289350556026953 0.319327731092437 0.0828402366863905],...
'BackgroundColor',[0.941176470588235 0.941176470588235 0.941176470588235],...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text21',...
'FontSize',9.99999999999989);

appdata = [];
appdata.lastValidTag = 'text22';

h41 = uicontrol(...
'Parent',h39,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','Image number',...
'Style','text',...
'Position',[0.0224089635854342 0.502368307506243 0.319327731092437 0.0828402366863905],...
'BackgroundColor',[0.941176470588235 0.941176470588235 0.941176470588235],...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text22',...
'FontSize',9.99999999999989);

appdata = [];
appdata.lastValidTag = 'text23';

h42 = uicontrol(...
'Parent',h39,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','Background number',...
'Style','text',...
'Position',[0.0280112044817927 0.636772364987223 0.319327731092437 0.136939983093829],...
'BackgroundColor',[0.941176470588235 0.941176470588235 0.941176470588235],...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text23',...
'FontSize',9.99999999999989);

appdata = [];
appdata.lastValidTag = 'text24';

h43 = uicontrol(...
'Parent',h39,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','Background method',...
'Style','text',...
'Position',[0.0252100840336135 0.881066532358314 0.319327731092437 0.0828402366863905],...
'BackgroundColor',[0.941176470588235 0.941176470588235 0.941176470588235],...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text24',...
'FontSize',9.99999999999989);

appdata = [];
appdata.lastValidTag = 'numStep';

h44 = uicontrol(...
'Parent',h39,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','6',...
'Style','edit',...
'Position',[0.375350140056022 0.289350556026953 0.42296918767507 0.118343195266272],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)PolariX_meas_GUI_export('numStep_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)PolariX_meas_GUI_export('numStep_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','numStep',...
'KeyPressFcn',blanks(0),...
'FontSize',9.99999999999989);

appdata = [];
appdata.lastValidTag = 'numSig';

h45 = uicontrol(...
'Parent',h39,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','10',...
'Style','edit',...
'Position',[0.375350140056022 0.466865348926361 0.42296918767507 0.118343195266272],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)PolariX_meas_GUI_export('numSig_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)PolariX_meas_GUI_export('numSig_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','numSig',...
'KeyPressFcn',blanks(0),...
'FontSize',9.99999999999989);

appdata = [];
appdata.lastValidTag = 'numBgr';

h46 = uicontrol(...
'Parent',h39,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','10',...
'Style','edit',...
'Position',[0.378151260504202 0.668048780879024 0.42296918767507 0.118343195266272],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)PolariX_meas_GUI_export('numBgr_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)PolariX_meas_GUI_export('numBgr_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','numBgr',...
'KeyPressFcn',blanks(0),...
'FontSize',9.99999999999989);

appdata = [];
appdata.lastValidTag = 'bgrMethod';

h47 = uicontrol(...
'Parent',h39,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String',{  'delay camera trigger'; 'block laser' },...
'Style','popupmenu',...
'Value',1,...
'Position',[0.372549019607843 0.801607529822389 0.439775910364146 0.159763313609467],...
'BackgroundColor',[0.941176470588235 0.941176470588235 0.941176470588235],...
'Callback',@(hObject,eventdata)PolariX_meas_GUI_export('bgrMethod_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)PolariX_meas_GUI_export('bgrMethod_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','bgrMethod',...
'KeyPressFcn',blanks(0),...
'FontSize',9.99999999999989);

appdata = [];
appdata.lastValidTag = 'txtOut';

h48 = uicontrol(...
'Parent',h1,...
'Units',get(0,'defaultuicontrolUnits'),...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Style','listbox',...
'Value',1,...
'Position',[452 20 409 658],...
'BackgroundColor',[0.941176470588235 0.941176470588235 0.941176470588235],...
'Callback',@(hObject,eventdata)PolariX_meas_GUI_export('txtOut_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'Enable','inactive',...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)PolariX_meas_GUI_export('txtOut_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','txtOut',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'FontSize',9.99999999999989);

appdata = [];
appdata.lastValidTag = 'comment';

h49 = uicontrol(...
'Parent',h1,...
'Units','characters',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','enter comment for plot',...
'Style','edit',...
'Position',[96.3333333333333 46.6 25.1666666666667 2.06666666666667],...
'Callback',@(hObject,eventdata)PolariX_meas_GUI_export('comment_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)PolariX_meas_GUI_export('comment_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','comment');


hsingleton = h1;


% --- Set application data first then calling the CreateFcn. 
function local_CreateFcn(hObject, eventdata, createfcn, appdata)

if ~isempty(appdata)
   names = fieldnames(appdata);
   for i=1:length(names)
       name = char(names(i));
       setappdata(hObject, name, getfield(appdata,name));
   end
end

if ~isempty(createfcn)
   if isa(createfcn,'function_handle')
       createfcn(hObject, eventdata);
   else
       eval(createfcn);
   end
end


% --- Handles default GUIDE GUI creation and callback dispatch
function varargout = gui_mainfcn(gui_State, varargin)

gui_StateFields =  {'gui_Name'
    'gui_Singleton'
    'gui_OpeningFcn'
    'gui_OutputFcn'
    'gui_LayoutFcn'
    'gui_Callback'};
gui_Mfile = '';
for i=1:length(gui_StateFields)
    if ~isfield(gui_State, gui_StateFields{i})
        error(message('MATLAB:guide:StateFieldNotFound', gui_StateFields{ i }, gui_Mfile));
    elseif isequal(gui_StateFields{i}, 'gui_Name')
        gui_Mfile = [gui_State.(gui_StateFields{i}), '.m'];
    end
end

numargin = length(varargin);

if numargin == 0
    % POLARIX_MEAS_GUI_EXPORT
    % create the GUI only if we are not in the process of loading it
    % already
    gui_Create = true;
elseif local_isInvokeActiveXCallback(gui_State, varargin{:})
    % POLARIX_MEAS_GUI_EXPORT(ACTIVEX,...)
    vin{1} = gui_State.gui_Name;
    vin{2} = [get(varargin{1}.Peer, 'Tag'), '_', varargin{end}];
    vin{3} = varargin{1};
    vin{4} = varargin{end-1};
    vin{5} = guidata(varargin{1}.Peer);
    feval(vin{:});
    return;
elseif local_isInvokeHGCallback(gui_State, varargin{:})
    % POLARIX_MEAS_GUI_EXPORT('CALLBACK',hObject,eventData,handles,...)
    gui_Create = false;
else
    % POLARIX_MEAS_GUI_EXPORT(...)
    % create the GUI and hand varargin to the openingfcn
    gui_Create = true;
end

if ~gui_Create
    % In design time, we need to mark all components possibly created in
    % the coming callback evaluation as non-serializable. This way, they
    % will not be brought into GUIDE and not be saved in the figure file
    % when running/saving the GUI from GUIDE.
    designEval = false;
    if (numargin>1 && ishghandle(varargin{2}))
        fig = varargin{2};
        while ~isempty(fig) && ~ishghandle(fig,'figure')
            fig = get(fig,'parent');
        end
        
        designEval = isappdata(0,'CreatingGUIDEFigure') || (isscalar(fig)&&isprop(fig,'GUIDEFigure'));
    end
        
    if designEval
        beforeChildren = findall(fig);
    end
    
    % evaluate the callback now
    varargin{1} = gui_State.gui_Callback;
    if nargout
        [varargout{1:nargout}] = feval(varargin{:});
    else       
        feval(varargin{:});
    end
    
    % Set serializable of objects created in the above callback to off in
    % design time. Need to check whether figure handle is still valid in
    % case the figure is deleted during the callback dispatching.
    if designEval && ishghandle(fig)
        set(setdiff(findall(fig),beforeChildren), 'Serializable','off');
    end
else
    if gui_State.gui_Singleton
        gui_SingletonOpt = 'reuse';
    else
        gui_SingletonOpt = 'new';
    end

    % Check user passing 'visible' P/V pair first so that its value can be
    % used by oepnfig to prevent flickering
    gui_Visible = 'auto';
    gui_VisibleInput = '';
    for index=1:2:length(varargin)
        if length(varargin) == index || ~ischar(varargin{index})
            break;
        end

        % Recognize 'visible' P/V pair
        len1 = min(length('visible'),length(varargin{index}));
        len2 = min(length('off'),length(varargin{index+1}));
        if ischar(varargin{index+1}) && strncmpi(varargin{index},'visible',len1) && len2 > 1
            if strncmpi(varargin{index+1},'off',len2)
                gui_Visible = 'invisible';
                gui_VisibleInput = 'off';
            elseif strncmpi(varargin{index+1},'on',len2)
                gui_Visible = 'visible';
                gui_VisibleInput = 'on';
            end
        end
    end
    
    % Open fig file with stored settings.  Note: This executes all component
    % specific CreateFunctions with an empty HANDLES structure.

    
    % Do feval on layout code in m-file if it exists
    gui_Exported = ~isempty(gui_State.gui_LayoutFcn);
    % this application data is used to indicate the running mode of a GUIDE
    % GUI to distinguish it from the design mode of the GUI in GUIDE. it is
    % only used by actxproxy at this time.   
    setappdata(0,genvarname(['OpenGuiWhenRunning_', gui_State.gui_Name]),1);
    if gui_Exported
        gui_hFigure = feval(gui_State.gui_LayoutFcn, gui_SingletonOpt);

        % make figure invisible here so that the visibility of figure is
        % consistent in OpeningFcn in the exported GUI case
        if isempty(gui_VisibleInput)
            gui_VisibleInput = get(gui_hFigure,'Visible');
        end
        set(gui_hFigure,'Visible','off')

        % openfig (called by local_openfig below) does this for guis without
        % the LayoutFcn. Be sure to do it here so guis show up on screen.
        movegui(gui_hFigure,'onscreen');
    else
        gui_hFigure = local_openfig(gui_State.gui_Name, gui_SingletonOpt, gui_Visible);
        % If the figure has InGUIInitialization it was not completely created
        % on the last pass.  Delete this handle and try again.
        if isappdata(gui_hFigure, 'InGUIInitialization')
            delete(gui_hFigure);
            gui_hFigure = local_openfig(gui_State.gui_Name, gui_SingletonOpt, gui_Visible);
        end
    end
    if isappdata(0, genvarname(['OpenGuiWhenRunning_', gui_State.gui_Name]))
        rmappdata(0,genvarname(['OpenGuiWhenRunning_', gui_State.gui_Name]));
    end

    % Set flag to indicate starting GUI initialization
    setappdata(gui_hFigure,'InGUIInitialization',1);

    % Fetch GUIDE Application options
    gui_Options = getappdata(gui_hFigure,'GUIDEOptions');
    % Singleton setting in the GUI MATLAB code file takes priority if different
    gui_Options.singleton = gui_State.gui_Singleton;

    if ~isappdata(gui_hFigure,'GUIOnScreen')
        % Adjust background color
        if gui_Options.syscolorfig
            set(gui_hFigure,'Color', get(0,'DefaultUicontrolBackgroundColor'));
        end

        % Generate HANDLES structure and store with GUIDATA. If there is
        % user set GUI data already, keep that also.
        data = guidata(gui_hFigure);
        handles = guihandles(gui_hFigure);
        if ~isempty(handles)
            if isempty(data)
                data = handles;
            else
                names = fieldnames(handles);
                for k=1:length(names)
                    data.(char(names(k)))=handles.(char(names(k)));
                end
            end
        end
        guidata(gui_hFigure, data);
    end

    % Apply input P/V pairs other than 'visible'
    for index=1:2:length(varargin)
        if length(varargin) == index || ~ischar(varargin{index})
            break;
        end

        len1 = min(length('visible'),length(varargin{index}));
        if ~strncmpi(varargin{index},'visible',len1)
            try set(gui_hFigure, varargin{index}, varargin{index+1}), catch break, end
        end
    end

    % If handle visibility is set to 'callback', turn it on until finished
    % with OpeningFcn
    gui_HandleVisibility = get(gui_hFigure,'HandleVisibility');
    if strcmp(gui_HandleVisibility, 'callback')
        set(gui_hFigure,'HandleVisibility', 'on');
    end

    feval(gui_State.gui_OpeningFcn, gui_hFigure, [], guidata(gui_hFigure), varargin{:});

    if isscalar(gui_hFigure) && ishghandle(gui_hFigure)
        % Handle the default callbacks of predefined toolbar tools in this
        % GUI, if any
        guidemfile('restoreToolbarToolPredefinedCallback',gui_hFigure); 
        
        % Update handle visibility
        set(gui_hFigure,'HandleVisibility', gui_HandleVisibility);

        % Call openfig again to pick up the saved visibility or apply the
        % one passed in from the P/V pairs
        if ~gui_Exported
            gui_hFigure = local_openfig(gui_State.gui_Name, 'reuse',gui_Visible);
        elseif ~isempty(gui_VisibleInput)
            set(gui_hFigure,'Visible',gui_VisibleInput);
        end
        if strcmpi(get(gui_hFigure, 'Visible'), 'on')
            figure(gui_hFigure);
            
            if gui_Options.singleton
                setappdata(gui_hFigure,'GUIOnScreen', 1);
            end
        end

        % Done with GUI initialization
        if isappdata(gui_hFigure,'InGUIInitialization')
            rmappdata(gui_hFigure,'InGUIInitialization');
        end

        % If handle visibility is set to 'callback', turn it on until
        % finished with OutputFcn
        gui_HandleVisibility = get(gui_hFigure,'HandleVisibility');
        if strcmp(gui_HandleVisibility, 'callback')
            set(gui_hFigure,'HandleVisibility', 'on');
        end
        gui_Handles = guidata(gui_hFigure);
    else
        gui_Handles = [];
    end

    if nargout
        [varargout{1:nargout}] = feval(gui_State.gui_OutputFcn, gui_hFigure, [], gui_Handles);
    else
        feval(gui_State.gui_OutputFcn, gui_hFigure, [], gui_Handles);
    end

    if isscalar(gui_hFigure) && ishghandle(gui_hFigure)
        set(gui_hFigure,'HandleVisibility', gui_HandleVisibility);
    end
end

function gui_hFigure = local_openfig(name, singleton, visible)

% openfig with three arguments was new from R13. Try to call that first, if
% failed, try the old openfig.
if nargin('openfig') == 2
    % OPENFIG did not accept 3rd input argument until R13,
    % toggle default figure visible to prevent the figure
    % from showing up too soon.
    gui_OldDefaultVisible = get(0,'defaultFigureVisible');
    set(0,'defaultFigureVisible','off');
    gui_hFigure = matlab.hg.internal.openfigLegacy(name, singleton);
    set(0,'defaultFigureVisible',gui_OldDefaultVisible);
else
    % Call version of openfig that accepts 'auto' option"
    gui_hFigure = matlab.hg.internal.openfigLegacy(name, singleton, visible);  
%     %workaround for CreateFcn not called to create ActiveX
%         peers=findobj(findall(allchild(gui_hFigure)),'type','uicontrol','style','text');    
%         for i=1:length(peers)
%             if isappdata(peers(i),'Control')
%                 actxproxy(peers(i));
%             end            
%         end
end

function result = local_isInvokeActiveXCallback(gui_State, varargin)

try
    result = ispc && iscom(varargin{1}) ...
             && isequal(varargin{1},gcbo);
catch
    result = false;
end

function result = local_isInvokeHGCallback(gui_State, varargin)

try
    fhandle = functions(gui_State.gui_Callback);
    result = ~isempty(findstr(gui_State.gui_Name,fhandle.file)) || ...
             (ischar(varargin{1}) ...
             && isequal(ishghandle(varargin{2}), 1) ...
             && (~isempty(strfind(varargin{1},[get(varargin{2}, 'Tag'), '_'])) || ...
                ~isempty(strfind(varargin{1}, '_CreateFcn'))) );
catch
    result = false;
end


